// Display copy only. Original posts and collected evidence are never translated.
(function(root) {
  const en = {
    '공식 일정 · 고정':'Official schedule · Pinned',
    '행사 일정':'Event schedule', '행사 예정 · 고정':'Upcoming · Pinned', '진행 중 · 고정':'Live · Pinned',
    '관련 글 보기':'Related posts', '감지한 소식 · 리셋 우선':'Detected updates · Resets first',
    '표시 시각은 게시 시각입니다. 실제 지급·계정 반영 시각은 별도 확인이 필요합니다.':'The displayed time is the post time. Check your account separately for the actual grant or reset time.',
    '이미 지난 일정일 수 있습니다.':'The scheduled time may already have passed.',
    '작성자가 리셋 완료를 알림 · 내 계정 반영은 잔여량 조회로 확인':'The author reports a completed reset. Check your remaining quota to confirm it reached your account.',
    '리셋권 지급 안내 · 자동 한도 리셋과 구분':'Credit grant notice. A grant does not automatically reset your quota.',
    '공식 일정 ↗':'Official schedule ↗', '키노트':'Keynote', '종료 · 한국':'Ends · Korea', '시각 미정':'Time unconfirmed',
    '종료 미정 · 행사일 종료까지 임시 고정':'End unconfirmed · Pinned through the event day',
    "날짜 추정":"Date inferred",
    "다음":"Next",
    "이번":"This",
    "암시·출시·행사 후보 알림":"Hint, launch and event alerts",
    "OpenAI, Tibo, VB의 원글과 답글 목록을 각각 확인하고 긴 본문을 펼쳐 읽습니다. 목록별 최대 24회 스크롤, 작성자별 최대 160개, 대화 원문 최대 3개를 확인합니다. 최대 270초 동안 비활성 탭을 열었다 닫으며 같은 Chrome의 X 로그인이 필요할 수 있습니다. 공개 본문·시각·링크·작성자 사진 주소·선행 대화만 기기에 보관하며 DM·쿠키·로그인 정보는 읽지 않습니다. 최근 7일을 목표로 확인하지만 전체 수집을 보장하지 않습니다.":"Reads public posts and replies from OpenAI, Tibo and VB, including expanded text and author photos. Limited to 24 scrolls per timeline, 160 posts per author, 3 conversations and 270 seconds. Opens only its own inactive X tab; X login may be required. Stores public text, timestamps, links, profile-image URLs and preceding context locally. Does not read DMs or credentials. Targets the past 7 days; completeness is not guaranteed.",
    "리셋 암시·제품 예고와 날짜·요일·시각이 있는 행사 소식을 알립니다. 같은 행사는 최초 일정·변경·취소 때만 알립니다. 출시·행사는 리셋 확정이 아닙니다. 기본 꺼짐. 최근 글·저장된 복귀 범위에 적용하며 사진·영상이나 불명확한 표현은 놓칠 수 있습니다.":"Alerts on reset hints, product teasers and events with a date, weekday or clock time. Each event alerts only for its first schedule, changes or cancellation. Launches/events do not confirm resets. Off by default. Recent posts and saved catch-up windows apply; image/video text or unclear wording may be missed.",
    "리셋·출시 소식":"Reset & launch news",
    "행사":"Event",
    "출시":"Launch",
    "리셋 미확인":"Reset unconfirmed",
    "OpenAI · Tibo · VB 수집 꺼짐":"OpenAI · Tibo · VB monitoring off",
    "새 리셋·출시·행사 소식이 없어요":"No new reset, launch or event news",
    "OpenAI · Tibo · VB의 리셋·출시·행사 관련 글을 표시합니다.":"Shows reset, launch and event posts from OpenAI, Tibo and VB.",
    "OpenAI · Tibo · VB 수집 연결":"OpenAI · Tibo · VB collection",
    "OpenAI · Tibo · VB의 Codex 소식 · 1.00":"OpenAI · Tibo · VB news · 1.00",
    "OpenAI, Tibo, VB의 공개 리셋·제품 출시·행사 소식을 확인합니다. 출시·행사만으로 리셋을 확정하지 않습니다.":"Monitors public reset, launch and event posts from OpenAI, Tibo and VB. Launches and events do not confirm a reset.",
    '자동 확인 실패 · 기존 기준으로 표시 중':'Automatic check failed · Showing the previous basis',
    '자동 확인을 완료하지 못했어요. 기존 기준을 유지합니다.':'Automatic check did not complete. The previous basis is preserved.',
    "Chat 추정 잔여량":"Estimated Chat remaining",
    "한도 기준 선택":"Select allowance basis",
    "한도 기준 선택 필요":"Select your plan to calculate remaining",
    "현재 계정의 요금제":"Plan for this account",
    "자동 확인":"Detect automatically",
    "직접 선택 기준 · 변경":"Selected plan · Change",
    "직접 선택 기준":"Selected plan",
    "최근 확인 기준 · 재확인 필요":"Last verified plan · Recheck needed",
    "요금제 자동 확인 · 변경":"Verified plan · Change",
    "선택은 이 계정에만 적용되며, 구독을 변경하지 않습니다.":"Applies only to this account. Does not change your subscription.",
    "로그인 계정과 같은 유형의 요금제만 선택할 수 있어요.":"Only plans matching your signed-in account type can be selected.",
    "자동 확인 실패 · 위에서 요금제를 선택해 주세요.":"Automatic check failed. Select your plan above.",
    "저장했습니다.":"Saved.",
    "저장하지 못했어요. 계정을 확인하고 다시 선택해 주세요.":"Could not save. Check your account and select again.",
    "계정 기록 기반 추정입니다. 삭제·임시 대화와 공식 초기화 시각 차이로 실제 잔여량과 다를 수 있습니다.":"Estimated from account history. Missing chats and reset timing can differ from the actual allowance.",
    "일간":"Daily",
    "월간":"Monthly",
    "사용 ·":"Used ·",
    '계정의 요금제와 Astra·Sol Pro·일반 Sol·Luna 사용을 구분합니다. 다른 기기는 아래 기록 동기화를 켜면 포함됩니다. 팝업의 지금 확인으로 요금제와 기록을 함께 갱신합니다. 잔여량은 추정이며, 끄면 모든 Chat 집계 기록을 삭제합니다.':'Checks the account plan and separates Astra, Sol Pro, standard Sol and Luna usage. Enable history sync below to include other devices. Check now refreshes both plan and history. Remaining counts are estimates. Disabling deletes all Chat counts.',
    'Chat · 모델별 사용량':'Chat · Model usage', 'Sol 일반':'Standard Sol',
    '워크스페이스별 한도':'Workspace-specific limits', '고정 잔여 횟수 미공개':'No fixed remaining count published',
    '잔여량·소식·요금제·기록 확인 중…':'Checking quota, news, plan and history…',
    '요금제 확인 중…':'Checking plan…', '요금제 화면 로딩 실패 · 요금제 확인으로 다시 연결':'Plan page did not load · Reconnect to check your plan',
    '요금제 확인은 완료하지 못했어요.':'The plan check did not complete.', 'Chat 기록 동기화는 다시 확인해 주세요.':'Please retry Chat history sync.',
    '선택 기능 · Codex 기준 로컬 집계':'Optional · Local count since Codex reset',
    'Chat과 Codex의 공식 한도는 별도입니다. 기본은 꺼짐이며, 켜면 Codex 회복 시각 이전 기록을 로컬 집계에서 제외합니다. Chat의 실제 잔여량 확인에는 사용하지 마세요.':'Chat and Codex have separate allowances. Off by default. Enabling excludes records before the Codex recovery time from local counts. Do not use it as the actual remaining Chat allowance.',
    '국가 선택':'Select country',
    '화면과 알림을 원하는 방식으로 맞춰보세요.':'Customize your display and notifications.',
    '팝업과 설정에 함께 적용되며 자동 저장됩니다.':'Applies to the popup and settings. Saved automatically.',
    'Tibo · VB 리셋 소식':'Tibo · VB updates', 'Tibo · VB 수집 연결':'Tibo · VB sources',
    'Tibo · VB의 Codex 소식':'Tibo · VB on Codex', 'Tibo · VB 수집 꺼짐':'Tibo · VB monitoring off',
    'Tibo와 VB의 원글과 답글 목록을 각각 확인하고 긴 본문을 펼쳐 읽습니다. 목록별 최대 12회 스크롤, 중복 제외 최대 160개, 대화 원문 최대 3개를 확인합니다. 최대 180초 동안 비활성 탭을 열었다 닫으며 같은 Chrome의 X 로그인이 필요할 수 있습니다. 공개 본문·시각·링크·선행 대화만 기기에 보관하며 DM·쿠키·로그인 정보는 읽지 않습니다. 최근 7일을 목표로 확인하지만 전체 수집을 보장하지 않습니다.':'Checks posts and replies from Tibo and VB separately, expanding long posts. Up to 12 scrolls per timeline, 160 unique posts and 3 conversations per check. Opens temporary background tabs for up to 180 seconds; X sign-in in this Chrome may be required. Only public text, dates, links and preceding public conversation are kept locally. No DMs, cookies or credentials are read. Targets the last 7 days; coverage is not guaranteed.',
    '직접 켜면 ChatGPT 로그인 상태로 잔여량을 조회합니다. 끄면 진행 중인 조회와 계정 데이터 저장을 중단하고 기존 데이터를 지웁니다.':'Enable to read quota through your ChatGPT session. Disabling stops requests and removes stored account data.',
    '같은 Chrome의 ChatGPT 계정과 현재 구독을 확인합니다. 이 Chrome에서 보낸 새 응답의 모델 정보로 Astra·Sol Pro를 구분하며 계정별 기록을 분리합니다. 다른 기기의 사용분은 아래 계정 기록 동기화를 켜야 확인할 수 있습니다. 잔여 횟수는 추정치이며, 끄면 모든 Chat 집계 기록을 삭제합니다.':'Checks the ChatGPT account and subscription in this Chrome. Counts observed Astra and Sol Pro responses separately per account. Enable account history sync below to include other devices. Remaining messages are estimates. Disabling deletes all local Chat counts.',
    '직접 켜면 현재 계정에 동기화된 최근 30일 기록을 조회합니다. 응답에는 대화 본문이 포함될 수 있지만 본문은 저장·출력·외부 전송하지 않고, 모델·사용 시각·중복 확인용 해시만 집계합니다. 삭제·임시 대화는 빠질 수 있습니다. 한 번에 최대 20개 대화를 확인하며 다음 확인 때 이어갑니다. 끄면 가져온 집계와 동기화 기록을 삭제합니다.':'Enable to read the last 30 days of synced account history. Responses may contain conversation text, but text is not stored, logged or sent elsewhere. Only model, timestamp and a deduplication hash are counted. Deleted and temporary chats may be missing. Checks up to 20 conversations per run, then continues next time. Disabling removes imported counts and sync records.',
    '내 잔여량 조회와 Chat 카운터가 켜져 있을 때, 같은 계정의 5시간 또는 주간 잔여량 회복을 확인하면 Astra·Sol Pro 기록을 새로 집계합니다. PC를 다시 켠 뒤 확인한 리셋도 반영합니다. Chat 서버 한도의 초기화를 확인하는 기능은 아니며, 잔여 횟수는 추정치입니다.':'When account quota and Chat counting are enabled, observed 5-hour or weekly quota recovery starts a new local Astra/Sol Pro count. Includes recovery observed after restarting your PC. This does not verify a Chat server quota reset; remaining messages are estimates.',
    'Tibo와 VB의 공개 글을 주요 리셋 예고 자료로 참고합니다.':'Uses public posts by Tibo and VB as reset signals.',
    '5시간·주간 잔여량이 100%로 회복되면 알립니다. 리셋 주기가 바뀌고 잔여량이 늘어난 경우 현재 잔여량으로 알립니다. 처음 연결한 계정은 비교 기준만 저장합니다.':'Notifies when 5-hour or weekly quota returns to 100%, or when its reset window changes and remaining quota increases. The first reading is saved as a baseline.',
    'Chrome 시작 또는 긴 조회 공백 후 같은 계정의 회복을 확인하면 확장의 방해 금지 시간에도 알립니다. 비교 기록은 최대 30일 보관합니다. 인터넷 연결 실패 시 재시도합니다. Chrome이 실행되어야 하며 Windows의 알림 허용 설정을 따릅니다.':'After Chrome starts or a long gap, notifies about recovery on the same account, even during the extension’s quiet hours. Keeps comparison records for up to 30 days and retries network failures. Chrome must be running; Windows notification settings apply.',
    'Chrome을 다시 켰을 때 놓친 예고·암시를 해당 알림 항목이 켜져 있으면 한 번 알립니다. 늦게 수집한 암시도 대상입니다. 복귀 알림은 확장 방해 금지 시간을 예외 처리합니다. 암시 후보는 최근 7일·최대 3개이며 리셋 확정이 아닙니다. 아래 후보 알림을 꺼도 팝업에는 표시됩니다.':'On return, notifies once about missed announcements or hints if those alerts are enabled. Bypasses extension quiet hours. Covers up to 3 hints from the last 7 days, including late collection. Hints are unconfirmed and remain visible even with hint notifications off.',
    '은유·리셋 문맥의 답글과 제품 공개 시각·짧은 요일+시각 답글을 후보로 알립니다. 출시·리셋 확정은 아닙니다. 기본 꺼짐. 켜면 다음 확인에서 최근 7일 후보도 한 번 알릴 수 있습니다. 새로운 비유·사진·불명확한 문맥은 놓칠 수 있습니다.':'Optional alerts for metaphors, reset-related replies and launch-time clues. These do not confirm a release or reset. Off by default. Enabling may notify once about hints from the last 7 days. New metaphors, images and unclear context may be missed.',
    '기준에 맞는 예고·후속 조치·완료·리셋권 지급 공지를 한 번 알립니다. 내 계정 반영은 잔여량 조회로 별도 확인합니다.':'Notifies once about qualifying reset announcements, follow-up fixes, completed resets and banked reset grants. Your own quota recovery is checked separately.',
    '기존 예고와 연결된 연기·일정 변경을 알립니다. 은유 후보는 후보 알림을 켠 경우에만, 명시 예고는 예고 알림을 켠 경우에만 알립니다. 답글 연결 정보가 없으면 연결 추정으로 표시합니다.':'Notifies about postponements linked to an earlier announcement. Hint changes require hint alerts; explicit announcements require reset alerts. Inferred links are labeled when direct reply references are absent.',
    '기본 공개 피드는 로그인 없이 확인합니다. 선택 기능인 X 직접 확인은 X 로그인이 필요할 수 있습니다. 내 잔여량 조회는 직접 켰을 때만 작동하며, 끄면 계정 데이터를 지웁니다.':'Public feeds require no sign-in. Optional direct X reading may require X sign-in. Account quota is read only when enabled; disabling removes account data.',
    '계정 기능을 직접 켠 경우에만 조회합니다. ChatGPT 페이지에 스크립트를 주입하지 않습니다.':'Quota requests run only after opt-in. The quota reader does not inject scripts into ChatGPT pages.',
    '♢ 로그인 토큰은 조회 요청 중에만 사용하고 저장소에 보관하지 않습니다. 공개 정보 제공처에는 토큰·계정 정보를 보내지 않습니다.':'Sign-in tokens are used only during requests and are not kept in storage. Tokens and account information are never sent to public feed providers.',
    'MIT 라이선스의 비공식 한국어 확장프로그램입니다. 보안 강화판은 페이지 코드 주입과 토큰 저장을 제거하고 통신·링크·메시지를 제한합니다. 계정 조회만 하며 리셋권을 자동 사용하지 않습니다.':'An unofficial MIT-licensed extension. Requests, links and messages are restricted. Tokens are not stored. Account features are read-only and never spend reset credits automatically.',
    'codex-reset-watchdog와 codex-reset-watcher에서 영감을 받았습니다.':'Inspired by codex-reset-watchdog and codex-reset-watcher.',
    '테스트 기능을 준비하고 있습니다. 이 문구가 바뀌지 않으면 설정 탭을 F5로 새로고침해 주세요.':'Preparing the notification test. If this stays visible, reload this settings tab with F5.',
    '알림을 받을 신뢰도':'Alert confidence', '어느 수준의 공개 소식부터 알림을 받을지 선택하세요.':'Choose the minimum confidence for public signals.',
    '공개 글과 기록에서 리셋 단서와 예상 시점을 확인합니다.':'Checks public posts and history for reset clues and timing.',
    '공식 장애, 한도 이상, 복구 상황을 참고합니다.':'References official incidents and service recovery.',
    '사용자 수 이정표와 과거 리셋 간격을 참고합니다.':'References user milestones and historical reset intervals.',
    '사용자의 한도 관련 제보는 낮은 가중치의 참고 자료로만 사용합니다.':'User reports are used only as low-weight context.',
    '한국 표준시: Asia/Seoul · 미국 서부: America/Los_Angeles':'Korea: Asia/Seoul · US Pacific: America/Los_Angeles',
    '만료가 가까워지면 사용 안내를 표시합니다.':'Shows guidance when reset credits are close to expiry.',
    '한도 때문에 작업이 막혔거나 잔여량이 적을 때 알립니다.':'Notifies when quota is low or blocks your work.',
    '선택한 시간 동안 긴급하지 않은 알림 줄이기':'Reduce nonurgent notifications during these hours.',
    '예고 시간보다 늦어질 수 있어요':'Resets may arrive later than announced',
    '조회된 정보가 없어요':'No quota data yet', '초기화 시각 확인 전':'Reset time unknown',
    '계정 연결 후 요금제와 사용 모델을 확인합니다.':'Connect your account to check your plan and models.',
    '현재 로그인 계정 자동 확인 · 임의 한도 적용 없음':'Reads your signed-in plan; no assumed quota.',
    '로컬 카운터 동기화입니다. Chat 서버의 실제 리셋·잔여량을 확인한 값은 아닙니다.':'Local counter sync only; not a verified Chat server reset or remaining quota.',
    '후보는 미확정 · Chat 잔여량은 추정':'Hints are unconfirmed · Chat counts are estimates',
    '답글 직접 확인 꺼짐 · 설정에서 연결':'Direct replies off · Connect in settings',
    'X 수집 확인 필요 · 설정 확인':'Check X connection in settings',
    '이전 수집 기록 · 지금 확인을 눌러 주세요':'Older scan · Press Check now',
    '수집 오류 · 보관된 소식':'Collection error · Saved updates',
    '소식을 불러오지 못했어요':'Could not load updates', '최신 글 수집을 확인해 주세요':'Check the latest collection status',
    '새 리셋 소식이 없어요':'No new reset updates', '새 소식을 확인하고 있어요':'Checking for updates',
    '미리보기 · 예시 데이터 · 실제 알림 없음':'Preview · Example data · No real notifications',
    'Codex 리셋 레이더 · 한국어 설정':'Codex Reset Radar · Settings', 'Codex 리셋 레이더 · 한국어':'Codex Reset Radar',
    '설정 항목':'Settings sections', 'X 공개 페이지 직접 확인':'Read public X pages',
    '내 잔여량·리셋권':'My quota and reset credits', 'Chat 사용 횟수 카운트':'Count Chat usage',
    '다른 기기 사용분은 계정 기록 연결 후 확인':'Connect account history to include other devices',
    'ChatGPT 연결':'ChatGPT connection', '잔여량이 연결되어 있습니다.':'Quota is connected.',
    '커뮤니티 리셋 기록':'Community reset history', '최근 읽은 글:':'Latest collected post:',
    '전체 글 수집을 보장하지 않으며 리셋 관련 소식만 팝업에 표시합니다.':'Coverage is limited. Only reset-related posts appear in the popup.',
    '중복 제외':'Unique posts', '일부 대화 확인 실패':'Some conversations could not be read', '본문 일부 생략':'Partly truncated',
    '테스트 버튼 준비 완료. 테스트 버튼으로 Windows 알림을 확인하세요.':'Ready. Use the test button to check Windows notifications.',
    '실행 코드 확인 불가':'Running version unavailable', '실행 코드 응답 없음. 확장과 이 설정 탭을 새로고침해 주세요.':'No response from the worker. Reload the extension and this tab.',
    'chrome://extensions/에서 확장을 새로고침한 뒤 이 설정 탭도 F5로 갱신해 주세요.':'Reload the extension at chrome://extensions/, then press F5 in this settings tab.',
    '확장 방해 금지 중':'Extension quiet hours active', '최근 전달:':'Last delivery:', 'Chrome 접수':'Accepted by Chrome',
    '잔여량 100% 회복 알림':'Quota recovery alerts', '방해 금지 시간 사용':'Enable quiet hours',
    '방해 금지 시작 시간':'Quiet hours start', '방해 금지 종료 시간':'Quiet hours end', '방해 금지 시간':'Quiet hours',
    '로컬 데이터 지우기':'Clear local data', '15분마다':'Every 15 minutes', '30분마다':'Every 30 minutes', '60분마다':'Every hour', '2시간마다':'Every 2 hours',
    '화면 v':'UI v', '실행 v':'Worker v', '후보 알림':'Hint alerts', '알림 허용':'Notifications allowed', '알림 차단':'Notifications blocked',
    '켜짐':'On', '대화':'Conversations', '대기':'Pending', '실패':'Failed',
    '조회:':'Checked:', '잔여량':'remaining quota', '감지한 소식 · 최신순':'Detected updates · Newest first',
    '시간대 미표기':'Time zone unspecified', '한국 시각 미정':'Korea time unknown', '일정 미정':'Time not announced',
    '리셋 종류 미확인':'Reset type unspecified', '일반 + Banked reset':'Quota + banked reset', '일반 리셋':'Quota reset',
    'reset 완료':'reset done', '지급 안내':'Credit grant', '완료 공지':'Completion post',
    '리셋 후속':'Reset update', '후속 안내':'Follow-up post',
    '리셋 반영 수정 안내':'Reset propagation fix', '리셋 반영 조사·보완':'Reset investigation and remediation',
    '리셋 반영 문제 조사·보완 안내 · 추가 리셋 여부·시각 미확정':'Reset propagation investigation and remediation · additional reset and timing unconfirmed',
    '리셋 반영 문제 수정 안내 · 추가 리셋 지급·내 계정 반영은 별도 확인':'Reset propagation fix · additional grants and your account recovery need separate confirmation',
    '원문 보기 ↗':'View post ↗', '원문 열림 ↗':'Post opened ↗', '다시 열기 ↗':'Try again ↗', '여는 중…':'Opening…',
    '리셋권 · 상태':'Credits · Status', '계정 기록 동기화 · 다른 기기 포함':'Sync account history · All devices',
    'Chat · 계정 연결 및 모델별 카운터':'Chat · Account and model counts', 'Codex 리셋 시 Chat 카운터도 초기화':'Restart Chat counters on Codex reset',
    '리셋 예고·후속·완료·리셋권 공지 알림':'Reset announcements, updates and credit grants', '은유·암시 후보 알림':'Metaphor and hint alerts',
    '다시 켰을 때 놓친 회복 바로 알림':'Catch up on quota recovery after restart', '놓친 공개 소식 복귀 알림':'Catch up on missed public updates',
    '잔여량 회복 알림':'Quota recovery alerts', '잔여량 부족 시 사용 안내':'Low quota guidance',
    '리셋 일정 변경 알림':'Schedule change alerts', 'X 글·답글 직접 확인 · 선택':'Read X posts and replies · Optional',
    '내 잔여량·리셋권(선택)':'My quota and reset credits · Optional', '글·답글 수집 상태':'Post and reply collection',
    'ChatGPT 로그인 상태(선택, 백그라운드 조회)':'ChatGPT session · Optional background requests',
    '공개 출처 4개':'4 public sources', '정보 출처·반영 비중':'Sources and weights',
    '테마를 저장하지 못했어요. 다시 선택해 주세요.':'Could not save the theme. Try again.',
    '테마를 저장했습니다.':'Theme saved.', '언어를 저장하지 못했어요. 다시 선택해 주세요.':'Could not save the language. Try again.',
    '언어를 저장했습니다.':'Language saved.', '화면 테마':'Theme', '국가 · 언어':'Country · Language',
    '시스템 설정':'System', '시스템 따름':'System', '라이트 모드':'Light', '다크 모드':'Dark',
    '리셋 레이더':'Reset Radar', '설정 열기':'Open settings', '설정':'Settings', '테마':'Theme', '라이트':'Light', '다크':'Dark', '시스템':'System',
    '데이터·개인정보':'Data & privacy', '감시 설정':'Monitoring', '감지 방식과 한계':'Detection limits', '정보':'About',
    '남은 사용량':'Remaining quota', '미확인':'Unknown', '계정 조회 꺼짐':'Account lookup off', '계정 연결 후 표시':'Connect to view',
    '계정 연결 꺼짐':'Account disconnected', '계정 확인 전':'Account not checked', '요금제 다시 확인':'Check plan again', '요금제 확인':'Check plan',
    '계정 기록 연결':'Connect history', '계정 연결':'Connect account', '연결 확인':'Check connection', '지금 동기화':'Sync now',
    'ChatGPT 로그인':'Sign in to ChatGPT', 'ChatGPT 열기':'Open ChatGPT', '연결 상태 확인 중…':'Checking connection…',
    '5시간':'5-hour', '주간':'Weekly', '리셋권':'Reset credits', '사용 안내':'Guidance', '알림 켜짐':'Alerts on', '알림 꺼짐':'Alerts off',
    '아직 확인하지 않음':'Not checked yet', '지금 확인':'Check now', '확인 중…':'Checking…', '확인했습니다.':'Checked.',
    '소식 확인 꺼짐':'Updates off', '원문 보기':'View post', '공개 소식 확인':'Check public updates', '공개 리셋 소식':'Public reset updates',
    '참고 예상 · 확정 아님':'Estimated timing · Unconfirmed', '리셋 일정 변경':'Reset schedule changed', '리셋 일정 연기':'Reset postponed',
    '변경 안내':'Change notice', '이전 예고 확인':'Earlier announcement', '변경 글 ↗':'Update ↗', '이전 글 ↗':'Earlier post ↗',
    '확인할 항목':'Monitor', '확인 방식':'Checking', '확인 전':'Not checked', '확인 간격':'Check interval',
    '브라우저 실행 중 주기적으로 확인':'Checks periodically while Chrome is running', '알림 연결 확인':'Notification connection',
    'Windows 알림 테스트':'Test Windows notifications', '실행 코드 연결 확인 중…':'Checking running version…',
    '리셋권 만료 알림':'Credit expiry alerts', '알림 설정':'Notifications', '테스트 알림':'Test notification',
    '정보 출처':'Sources', '공개 정보':'Public data', '시간대 직접 입력':'Custom time zone', '시간 표시':'Time display', '시간대':'Time zone',
    '한국어판':'Community edition', '한국어':'Korean', '후보':'Hint', '수동':'Manual', '전체':'All',
    '높음만':'High only', '중간 이상':'Medium or higher', '저장됨':'Saved', '저장 중…':'Saving…', '알림':'Notifications',
    '추정 잔여':'Est. left', '모델별 추정':'Est. by model', '기록 집계':'History count', 'Chrome 관측':'Observed in Chrome',
    '잔여 미확인':'Remaining unknown', '일간·주간 한도 함께 반영':'Daily and weekly limits', '한도 확인 전':'Limit not checked',
    '공유 월':'Shared monthly', '공유 주':'Shared weekly', '자동 확인됨':'Verified',
    'Codex 연동 초기화':'Counter reset with Codex', 'Codex 리셋 확인 시 카운터 함께 초기화':'Counters restart on observed Codex reset',
    'Codex 리셋 연동 꺼짐':'Codex reset sync off', '다른 기기 기록 미연결':'Other-device history not connected',
    '최근 수집 글 없음':'No collected posts', '최근 수집 글:':'Latest collected post:', '최근 글':'Latest post',
    '수집 범위에서 리셋 관련 글만 표시합니다.':'Shows reset-related posts within the collected range.',
    '원글·답글':'Posts/replies', '수집 실패':'Collection failed', '설정 확인':'Check settings', '대기 중':'Waiting',
    '계정 기록 확인 중…':'Checking account history…', '원글':'Posts', '답글':'Replies',
    '한국':'Korea', '미 서부':'US Pacific', '추정':'Estimated', '게시':'posted', '기준':'as of',
    '월요일':'Monday', '화요일':'Tuesday', '수요일':'Wednesday', '목요일':'Thursday', '금요일':'Friday', '토요일':'Saturday', '일요일':'Sunday',
    '오늘 중':'Later today', '내일 아침':'Tomorrow morning', '내일':'Tomorrow', '다음 주':'Next week', '이번 주':'This week',
    '오늘 밤':'Tonight', '오늘 저녁':'This evening', '곧':'Soon', '오전':'AM', '오후':'PM', '초기화':'reset', '꺼짐':'Off',
  };
  const tables=new Map();
  function table(language){
    if(tables.has(language)) return tables.get(language);
    const reverse=new Map();
    for(const [key,value] of Object.entries(root.RadarTranslations?.ko || {}))
      if(!value.includes('{') && root.RadarTranslations[language]?.[key]) reverse.set(value,root.RadarTranslations[language][key]);
    const extra=root.RadarUiLocales?.[language] || {};
    const entries=Object.fromEntries(Object.entries(en).map(([ko,english])=>[ko,
      extra[english] || reverse.get(ko) || (english.endsWith(' ↗') && extra[english.slice(0,-2)] ? extra[english.slice(0,-2)]+' ↗' : english)]));
    const result={entries,reverse,pairs:Object.entries(entries).sort((a,b)=>b[0].length-a[0].length)};
    tables.set(language,result);return result;
  }
  function translate(value){
    if(root.RadarI18n.uiLanguage()==='ko-KR') return value;
    const language=root.RadarI18n.catalogLanguage();
    const {entries,reverse,pairs}=table(language);
    const trimmed=String(value).trim();
    if(entries[trimmed] || reverse.has(trimmed)) return String(value).replace(trimmed,entries[trimmed] || reverse.get(trimmed));
    let out=String(value);
    for(const [from,to] of pairs) out=out.split(from).join(to);
    if(language!=='en'){
      const units={ja:['件','件確認','回','個','残り','日','時間','分','最近','確認:'],zh_CN:['条','条已检查','次','个','剩余','天','小时','分钟','最近','已检查:'],fr:['posts','vérifiés','messages','éléments','restants','j','h','min','Dernier','Vérifié :'],es:['posts','revisados','mensajes','elementos','restantes','d','h','min','Último','Revisado:'],it:['post','verificati','messaggi','elementi','rimasti','g','h','min','Ultimo','Verificato:']}[language];
      if(units) return out.replace(/(\d+)건/g,'$1 '+units[0]).replace(/(\d+)개 확인/g,'$1 '+units[1]).replace(/(\d+)회/g,'$1 '+units[2]).replace(/(\d+)개/g,'$1 '+units[3])
        .replace(/남음/g,units[4]).replace(/(\d+)일/g,'$1 '+units[5]).replace(/(\d+)시간/g,'$1 '+units[6]).replace(/(\d+)분/g,'$1 '+units[7]).replace(/최근/g,units[8]).replace(/확인:/g,units[9]);
    }
    return out.replace(/(\d+)건/g,'$1 posts').replace(/(\d+)개 확인/g,'$1 checked').replace(/(\d+)회 남음/g,'$1 left')
      .replace(/(\d+)회 사용/g,'$1 used').replace(/(\d+)회/g,'$1 messages').replace(/(\d+)개/g,'$1 items')
      .replace(/(\d+)일/g,'$1d').replace(/(\d+)시간/g,'$1h').replace(/(\d+)분/g,'$1m').replace(/남음/g,'left').replace(/최근/g,'Last').replace(/확인:/g,'Checked:');
  }
  root.RadarUiCopy={translate,en,table};
  if(typeof module!=='undefined') module.exports=root.RadarUiCopy;
})(globalThis);
